---
env:
  es6: true
  node: true
extends:
- airbnb-base
- plugin:prettier/recommended
- plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
plugins:
- "@typescript-eslint"
- sort-keys-fix
- sort-destructure-keys
- typescript-sort-keys
rules:
  "@typescript-eslint/array-type": error
  "@typescript-eslint/brace-style":
  - error
  - 1tbs
  - allowSingleLine: true
  "@typescript-eslint/explicit-function-return-type": 'off'
  "@typescript-eslint/no-empty-function": warn
  "@typescript-eslint/no-redeclare":
  - error
  "@typescript-eslint/no-shadow": error
  "@typescript-eslint/no-unused-vars": error
  no-redeclare: 'off'
  no-shadow: 'off'
  react/jsx-no-bind: 'off'
  react/prop-types: 'off'
  arrow-body-style: 'off'
  brace-style:
  - error
  - 1tbs
  - allowSingleLine: true
  class-methods-use-this: 'off'
  consistent-return: 0
  curly:
  - error
  - multi-line
  eol-last: 2
  function-paren-newline: 0
  global-require: 0
  implicit-arrow-linebreak: 0
  import/extensions: 'off'
  import/no-cycle: warn
  import/no-extraneous-dependencies: 'off'
  import/no-unresolved: 'off'
  import/order:
  - error
  - alphabetize:
      caseInsensitive: true
      order: asc
    groups:
    - - builtin
      - external
    - parent
    - sibling
    - index
    - object
    newlines-between: always
  import/prefer-default-export: 'off'
  indent: 'off'
  max-classes-per-file: 'off'
  max-len: 'off'
  no-confusing-arrow: 'off'
  no-console:
  - warn
  - allow:
    - warn
    - error
    - info
    - debug
  no-continue: 'off'
  no-lonely-if: 'off'
  no-nested-ternary: 'off'
  no-plusplus:
  - error
  - allowForLoopAfterthoughts: true
  no-prototype-builtins: 'off'
  no-restricted-syntax: 'off'
  no-return-assign: 'off'
  no-unused-expressions: 0
  no-use-before-define: 0
  nonblock-statement-body-position: 0
  object-curly-newline: 'off'
  operator-assignment: 'off'
  operator-linebreak: 'off'
  prefer-destructuring:
  - error
  - AssignmentExpression:
      array: false
      object: false
    VariableDeclarator:
      array: false
      object: true
  prefer-template: 0
  prettier/prettier: error
  sort-destructure-keys/sort-destructure-keys: error
  sort-imports:
  - error
  - ignoreCase: true
    ignoreDeclarationSort: true
  sort-keys-fix/sort-keys-fix: error
  space-before-function-paren: 'off'
  typescript-sort-keys/interface: error
  typescript-sort-keys/string-enum: error
settings:
  import/resolver:
    node:
      extensions:
      - ".js"
      - ".jsx"
      - ".ts"
      - ".tsx"
